services:
  koobfood:
    image: koobfood
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: local
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/.venv
    command: uv run manage.py runserver 0.0.0.0:8000
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=koobfood
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 40s
  celery:
    image: koobfood
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: local
    command: /app/.venv/bin/celery -A koobfood worker --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
  beat:
    image: koobfood
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: local
    command: /app/.venv/bin/celery -A koobfood beat --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//  
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
  loki:
    image: grafana/loki:2.8.2
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - 3100:3100
    volumes:
      - loki_data:/loki
      - ./backend/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    depends_on:
      - db
      - rabbitmq
  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    ports:
      - 9080:9080
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - loki

volumes:
  db_data:
  loki_data:  